//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hiring_Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        public int id_offre { get; set; }
        public Nullable<int> id_recruteur { get; set; }
        public string type_contrat { get; set; }
        public string secteur { get; set; }
        public string profil { get; set; }
        public string poste { get; set; }
        public string rémunération { get; set; }
    }
}
